server:
  port: 8081
spring:
  application:
    name: hello
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://127.0.0.1:8000/eureka