server:
  port: 8080
spring:
  application:
    name: demo
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://127.0.0.1:8000/eureka

secret:
  map: "{127: 'asdfg', 256: 'qwert'}"

